---
init_commands: []
python_packages:
  - selenium
  - yfinance
system_packages:
  - chromium
  - chromium-chromedriver
  - py3-requests
  - py3-beautifulsoup4
  - py3-pandas
  - py3-numpy
  - py3-setuptools
  - py3-wheel
